language: go

sudo: false

before_script:
  - go get github.com/mattn/goveralls

script:
  - make test
  - $HOME/gopath/bin/goveralls -service=travis-ci -ignore='examples/*'

os:
  - linux
  - osx

go:
  - "1.4.x"
  - "1.5.x"
  - "1.6.x"
  - "1.7.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "tip"
